import Link from "next/link";
import { RocketLaunchIcon } from "@heroicons/react/24/solid";

export const metadata = { title: "Terms of Service — LaunchPilot" };

export default function TermsPage() {
  return (
    <div className="min-h-screen bg-white">
      <header className="border-b border-gray-100 py-4 px-6">
        <div className="max-w-4xl mx-auto flex items-center justify-between">
          <Link href="/" className="flex items-center gap-2">
            <div className="w-7 h-7 rounded-lg bg-brand-500 flex items-center justify-center">
              <RocketLaunchIcon className="w-3.5 h-3.5 text-white" />
            </div>
            <span className="font-bold text-gray-900">LaunchPilot</span>
          </Link>
        </div>
      </header>

      <main className="max-w-3xl mx-auto px-6 py-16">
        <h1 className="text-4xl font-bold text-gray-900 mb-4">Terms of Service</h1>
        <p className="text-gray-400 text-sm mb-12">Last updated: March 2026</p>

        <div className="prose prose-gray max-w-none space-y-8">
          <section>
            <h2 className="text-xl font-semibold text-gray-900 mb-3">Acceptance</h2>
            <p className="text-gray-600 leading-relaxed">
              By using LaunchPilot you agree to these terms. If you don't agree, don't use the service.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-gray-900 mb-3">Use of the service</h2>
            <p className="text-gray-600 leading-relaxed">
              LaunchPilot is a marketing automation tool. You're responsible for the content you approve and publish. Don't use the service to generate spam, misleading content, or anything that violates platform policies.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-gray-900 mb-3">Subscriptions and billing</h2>
            <p className="text-gray-600 leading-relaxed">
              Paid plans are billed monthly. You can cancel anytime from your billing settings. Refunds are handled on a case-by-case basis — email{" "}
              <a href="mailto:hello@launchpilot.io" className="text-brand-600 hover:underline">hello@launchpilot.io</a>.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-gray-900 mb-3">Intellectual property</h2>
            <p className="text-gray-600 leading-relaxed">
              Content generated by LaunchPilot belongs to you once you approve it. LaunchPilot retains no rights to content you generate through the service.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-gray-900 mb-3">Limitation of liability</h2>
            <p className="text-gray-600 leading-relaxed">
              LaunchPilot is provided "as is." We're not liable for any indirect, incidental, or consequential damages arising from use of the service.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-gray-900 mb-3">Contact</h2>
            <p className="text-gray-600 leading-relaxed">
              Questions?{" "}
              <a href="mailto:hello@launchpilot.io" className="text-brand-600 hover:underline">hello@launchpilot.io</a>
            </p>
          </section>
        </div>
      </main>
    </div>
  );
}
